### ISSUE TITLE
Add middle-click support

### ISSUE THREAD

**Issue by mikeconley** [mikeconley/tab-submit-basic#1]
via an anonymous comment posted on my blog:

"Could you enable the add-on to work with middle-click?"

**Comment by 20150131** [comment]
I'm anonymous. Thanks.

Um... will middle-click be enabled (any time soon)?

**Comment by MurzNN** [comment]
I wait this feature too! Is it possible to catch middle-click on submit in fresh Firefox versions?

**Comment by mikeconley** [comment]
This was fixed by commit 4a54f3 and will be part of the 0.5.0 release, which I just submitted to AMO. It will hopefully get through the review queue shortly.

**Comment by MurzNN** [comment]
Thanks, it works!
