### ISSUE TITLE
Middle-click no longer works

### ISSUE THREAD

**Issue by rvandermeulen** [mikeconley/tab-submit-basic#4]
Not sure exactly how this relates to #1 since it was definitely working for me at one point in time. I was able to track down the behavior change for me to when bug 1379466 landed.

In the past, I was able to middle-click the submit button on the [Release Tracking Report](https://bugzilla.mozilla.org/page.cgi?id=release_tracking_report.html) and have the results open in a new tab, but now only Ctrl+Click works. Note that in the past, I would have to whitelist BMO from Firefox' popup blocker for middle-click to work.

**Comment by mikeconley** [comment]
So the issue here is that in bug 1379466, we stopped dispatching click events for middle-clicks for content documents, since that was never part of the spec.

Instead, middle-clicks cause us to fire `auxclick` events. I'll update the WebExtension to listen for `auxclick` as well.

**Comment by mikeconley** [comment]
This was fixed by commit 4a54f3 and will be part of the 0.5.0 release, which I just submitted to AMO. It will hopefully get through the review queue shortly.
